/**
 * SentinelX ESP32 Serial & Hardware Telemetry Bridge
 * 
 * Automatically connects to ESP32 USB COM port (e.g. COM5),
 * reads raw Serial output at 115200 baud rate generated by sensors.ino,
 * parses calibrated sensor readings (Kalman ACS712 current, ADXL345 3-axis accel, DHT22 temp, RPM, Sound),
 * and streams real-time telemetry to the SentinelX API and Socket.IO dashboard.
 */

const http = require('http');
const https = require('https');
const readline = require('readline');
const path = require('path');

let SerialPort, ReadlineParser;
try {
  ({ SerialPort } = require('serialport'));
  ({ ReadlineParser } = require('@serialport/parser-readline'));
} catch (err) {
  try {
    ({ SerialPort } = require(path.join(__dirname, '../backend/node_modules/serialport')));
    ({ ReadlineParser } = require(path.join(__dirname, '../backend/node_modules/@serialport/parser-readline')));
  } catch (err2) {
    console.error('⚠️ Could not load serialport package natively. Will fall back to standard input.');
  }
}

const args = process.argv.slice(2);
function getArg(flag, defaultVal) {
  const idx = args.indexOf(flag);
  return idx !== -1 && args[idx + 1] ? args[idx + 1] : defaultVal;
}

const SERVER_URL = getArg('--url', 'http://localhost:5000/api/v1/telemetry/ingest');
const DEVICE_ID = getArg('--device', 'ESP32_HARDWARE');
let targetPort = getArg('--port', null);

console.log('====================================================');
console.log(' 🔌 SentinelX ESP32 Serial & Hardware Bridge Started ');
console.log(` 📡 Target Server : ${SERVER_URL}`);
console.log(` 🆔 Device ID     : ${DEVICE_ID}`);
console.log('====================================================');

function parseSerialBlock(blockText) {
  const tempMatch = blockText.match(/Temperature\s*:\s*([\d\.-]+)/i);
  const humMatch = blockText.match(/Humidity\s*:\s*([\d\.-]+)/i);
  const xMatch = blockText.match(/X\s*:\s*([\d\.-]+)/i);
  const yMatch = blockText.match(/Y\s*:\s*([\d\.-]+)/i);
  const zMatch = blockText.match(/Z\s*:\s*([\d\.-]+)/i);
  const rpmMatch = blockText.match(/RPM\s*:\s*([\d\.-]+)/i);
  const voltMatch = blockText.match(/Voltage\s*:\s*([\d\.-]+)/i);
  const curMatch = blockText.match(/Current\s*:\s*([\d\.-]+)/i);
  const soundMatch = blockText.match(/Sound ADC\s*:\s*([\d\.-]+)/i);

  if (!tempMatch && !rpmMatch && !curMatch && !voltMatch) return null;

  let ax = xMatch ? parseFloat(xMatch[1]) : 0.0;
  let ay = yMatch ? parseFloat(yMatch[1]) : 0.0;
  let az = zMatch ? parseFloat(zMatch[1]) : 1.0;

  // Scale normalization if ADXL345 16G raw multiplier > 16.0g
  if (Math.abs(ay) > 16.0) ay = ay / 32.0;
  if (Math.abs(ax) > 16.0) ax = ax / 32.0;
  if (Math.abs(az) > 16.0) az = az / 32.0;

  ax = Math.round(ax * 100) / 100;
  ay = Math.round(ay * 100) / 100;
  az = Math.round(az * 100) / 100;

  const totalMag = Math.sqrt(ax * ax + ay * ay + az * az);
  // Subtract 1.0g static Earth gravity vector to isolate dynamic machine vibration
  const dynamicVib = Math.abs(totalMag - 1.0);
  const vibVal = Math.max(0.01, Math.round(dynamicVib * 1000) / 1000);

  return {
    deviceId: DEVICE_ID,
    timestamp: new Date().toISOString(),
    temperature: tempMatch ? parseFloat(tempMatch[1]) : 28.5,
    humidity: humMatch ? parseFloat(humMatch[1]) : 58.2,
    voltage: voltMatch ? parseFloat(voltMatch[1]) : 12.3,
    current: curMatch ? Math.max(0, Math.round(parseFloat(curMatch[1]) * 1000) / 1000) : 0.0,
    rpm: rpmMatch ? parseFloat(rpmMatch[1]) : 1480,
    sound: soundMatch ? parseFloat(soundMatch[1]) : 320,
    vibration: vibVal,
    acceleration: { x: ax, y: ay, z: az },
  };
}

function sendTelemetryToServer(payload) {
  const dataString = JSON.stringify(payload);
  const urlObj = new URL(SERVER_URL);
  
  const options = {
    hostname: urlObj.hostname,
    port: urlObj.port || (urlObj.protocol === 'https:' ? 443 : 80),
    path: urlObj.pathname.replace(/\/+/g, '/'),
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Content-Length': Buffer.byteLength(dataString),
      'x-device-id': DEVICE_ID,
    },
  };

  const req = (urlObj.protocol === 'https:' ? https : http).request(options, (res) => {
    let body = '';
    res.on('data', (chunk) => body += chunk);
    res.on('end', () => {
      if (res.statusCode === 200) {
        console.log(`[${new Date().toLocaleTimeString()}] ✅ Ingested ESP32 Hardware: Temp=${payload.temperature}°C, Cur=${payload.current}A, RPM=${payload.rpm}, Sound=${payload.sound}, Accel=(${payload.acceleration.x}, ${payload.acceleration.y}, ${payload.acceleration.z})`);
      } else {
        console.log(`[${new Date().toLocaleTimeString()}] ⚠️ Ingestion Warning [${res.statusCode}]: ${body}`);
      }
    });
  });

  req.on('error', (err) => {
    console.error(`[${new Date().toLocaleTimeString()}] ❌ HTTP Connection Error:`, err.message);
  });

  req.write(dataString);
  req.end();
}

let serialBuffer = '';

function handleLine(line) {
  serialBuffer += line + '\n';
  if (line.includes('===============================') || line.includes('===============')) {
    const parsed = parseSerialBlock(serialBuffer);
    if (parsed) {
      sendTelemetryToServer(parsed);
    }
    serialBuffer = '';
  }
}

async function connectSerial() {
  const ports = await SerialPort.list();
  console.log(`🔍 Discovered ${ports.length} Serial COM Ports:`);
  ports.forEach((p) => console.log(`   - ${p.path} | ${p.manufacturer || 'Unknown Manufacturer'}`));

  if (!targetPort) {
    if (ports.length > 0) {
      // Pick COM5 if present, or first port
      const com5 = ports.find((p) => p.path.toUpperCase() === 'COM5');
      targetPort = com5 ? com5.path : ports[0].path;
    } else {
      targetPort = 'COM5'; // Default fallback
    }
  }

  console.log(`\n⚡ Connecting to ESP32 on port: ${targetPort} at 115200 baud...`);

  try {
    const port = new SerialPort({ path: targetPort, baudRate: 115200 });
    const parser = port.pipe(new ReadlineParser({ delimiter: '\n' }));

    port.on('open', () => {
      console.log(`✅ Serial Port ${targetPort} OPENED successfully! Streaming ESP32 telemetry...`);
    });

    port.on('error', (err) => {
      if (err.message.includes('Access denied')) {
        console.log(`\n====================================================`);
        console.log(` ⚠️ ${targetPort} is currently locked by Windows.`);
        console.log(` 💡 Quick 2-Step Fix:`);
        console.log(`   1. Unplug the ESP32 USB cable from your laptop and plug it back in.`);
        console.log(`      (This instantly clears the Windows serial driver lock)`);
        console.log(`   2. Close Arduino IDE or any serial monitor tools.`);
        console.log(`====================================================\n`);
        console.log(`🔄 SentinelX will automatically retry connecting to ${targetPort} in 5 seconds...\n`);
      } else {
        console.error(`❌ Serial Port Error on ${targetPort}:`, err.message);
      }
      setTimeout(connectSerial, 5000);
    });

    parser.on('data', (line) => {
      handleLine(line.trim());
    });
  } catch (err) {
    console.error(`❌ Failed to initialize SerialPort on ${targetPort}:`, err.message);
    setTimeout(connectSerial, 5000);
  }
}

// Enable standard input listening as a backup
const rl = readline.createInterface({ input: process.stdin, output: process.stdout, terminal: false });
rl.on('line', (line) => handleLine(line.trim()));

connectSerial();
